# Generated by Django 3.2.18 on 2023-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantID', models.CharField(max_length=100)),
                ('restaurantName', models.CharField(max_length=100)),
                ('restaurantRating', models.CharField(max_length=100)),
                ('restaurantCuisine', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('openingHours', models.CharField(max_length=100)),
                ('restaurantAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
