# Generated by Django 3.2.18 on 2023-03-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdb',
            old_name='restaurantName',
            new_name='name',
        ),
    ]
