# Generated by Django 4.1.7 on 2023-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_restaurantdb_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('restaurant_rating', models.CharField(max_length=3)),
                ('restaurant_review', models.CharField(max_length=100000)),
            ],
        ),
    ]
