# Generated by Django 4.1.7 on 2023-03-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant_name',
        ),
    ]
