# Generated by Django 4.1.7 on 2023-03-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_review_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant_rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
