# Generated by Django 4.1.7 on 2023-03-28 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_review_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
