# Generated by Django 4.1.7 on 2023-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_review_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
