# Generated by Django 3.2.18 on 2023-04-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_review_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
