# Generated by Django 3.2.18 on 2023-04-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_review_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
